# Change these first
owner: grycap # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
assignees:
  - micafer

sites:
  - name: IM-Dashboard
    url: https://appsgrycap.i3m.upv.es/im-dashboard/login
    icon: https://appsgrycap.i3m.upv.es/im-dashboard/static/images/favicon_io/favicon-32x32.png
    assignees:
      - micafer
  - name: IM Server
    url: https://appsgrycap.i3m.upv.es/im/version
    icon: https://appsgrycap.i3m.upv.es/im-dashboard/static/images/favicon_io/favicon-32x32.png
    assignees:
      - micafer
  - name: CloudTrail-Tracker
    url: https://cloudtrailtracker.cursocloudaws.net/
    icon: https://raw.githubusercontent.com/grycap/cloudtrail-tracker-ui/master/static/logos/favicon.ico
    assignees:
      - gmolto
  - name: OSCAR Cluster - Sandbox
    url: https://oscar.test.fedcloud.eu
    icon: https://raw.githubusercontent.com/grycap/oscar-dashboard/refs/heads/main/src/assets/logos/favicon.ico
    assignees:
      - slangarita
      - catttam
      - gmolto 
  - name: OSCAR Cluster - AI4EOSC
    url: https://inference.cloud.ai4eosc.eu
    icon: https://raw.githubusercontent.com/grycap/oscar-dashboard/refs/heads/main/src/assets/logos/favicon.ico
    assignees:
      - slangarita
      - catttam 
      - gmolto
  - name: OSCAR Cluster - iMagine
    url: https://inference-walton.cloud.imagine-ai.eu
    icon: https://raw.githubusercontent.com/grycap/oscar-dashboard/refs/heads/main/src/assets/logos/favicon.ico
    assignees:
      - slangarita
      - catttam 
      - gmolto
  - name: OSCAR Cluster - interTwin (GRNET)
    url: https://oscar-grnet.intertwin.fedcloud.eu
    icon: https://raw.githubusercontent.com/grycap/oscar-dashboard/refs/heads/main/src/assets/logos/favicon.ico
    assignees:
      - slangarita
      - catttam
      - esparig 
      - gmolto
  - name: OSCAR Cluster - interTwin (UKRI)
    url: https://oscar-ukri.intertwin.fedcloud.eu
    icon: https://raw.githubusercontent.com/grycap/oscar-dashboard/refs/heads/main/src/assets/logos/favicon.ico
    assignees:
      - slangarita
      - catttam
      - esparig 
      - gmolto
#  - name: EOSC IM Server Prod
#    url: https://kubeserver.vm.cesnet.cz/im/version
#    icon: https://appsgrycap.i3m.upv.es/im-dashboard/static/images/favicon_io/favicon-32x32.png
#    assignees:
#      - micafer
#  - name: EOSC IM Server Staging
#    url: https://kubeserver.vm.cesnet.cz/im-staging/version
#    icon: https://appsgrycap.i3m.upv.es/im-dashboard/static/images/favicon_io/favicon-32x32.png
#    assignees:
#      - micafer

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.grycap.net
  # baseUrl: /your-repo-name
  logoUrl: https://www.grycap.upv.es/wp-content/uploads/2018/01/logo-7.png
  name: GRyCAP Status
  introTitle: GRyCAP Status
  introMessage: Live status page of [GRyCAP](https://www.grycap.upv.es) services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
