# Change these first
owner: grycap # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: IM-Dashboard
    url: https://appsgrycap.i3m.upv.es:31443/im-dashboard/login
    icon: https://appsgrycap.i3m.upv.es:31443/im-dashboard/static/images/favicon_io/favicon-32x32.png
    assignees:
      - micafer
  - name: IM Server
    url: https://appsgrycap.i3m.upv.es:31443/im/version
    icon: https://appsgrycap.i3m.upv.es:31443/im-dashboard/static/images/favicon_io/favicon-32x32.png
    assignees:
      - micafer
  - name: Cloud Trail Tracker
    url: https://cloudtrailtracker.cursocloudaws.net/
    icon: https://raw.githubusercontent.com/grycap/cloudtrail-tracker-ui/master/static/logos/favicon.ico
    assignees:
      - gmolto
  - name: ReMindCare I3M
    url: https://remindcare.i3m.upv.es/
    icon: https://remindcare.i3m.upv.es/brain.png
    assignees:
      - darce-i3m
  - name: ECNP-CDM
    url: https://ecnp-cdm.i3m.upv.es
    icon: https://ecnp-cdm.i3m.upv.es/favicon.ico
    assignees:
      - darce-i3m

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.grycap.net
  # baseUrl: /your-repo-name
  logoUrl: https://www.grycap.upv.es/wp-content/uploads/2018/01/logo-7.png
  name: GRyCAP Status
  introTitle: GRyCAP Status
  introMessage: Live status page of [GRyCAP](https://www.grycap.upv.es) services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
