#!/bin/bash

README="README.md"

START=$(grep -n "<!--start: status pages-->" "$README" | head -1 | cut -d: -f1)
END=$(grep -n "<!--end: status pages-->" "$README" | head -1 | cut -d: -f1)

sed -n "1,$((START-1))p" "$README" > prefix
sed -n "$((END+1)),\$p" "$README" > suffix

while IFS= read -r row; do
    name=$(echo "$row" | sed 's/^[^[]*\[\([^]]*\)\].*/\1/')
    case "$name" in
        "IM-Dashboard"|"IM Server"|"CloudTrail-Tracker"|"GRyCAP Keycloak")
            echo "$row" >> tools
            ;;
        *)
            echo "$row" >> clusters
            ;;
    esac
done < <(grep '^| <img' "$README")

cat prefix > "$README"
cat >> "$README" << 'MARKER'
<!--start: status pages-->
<!-- This summary is generated by Upptime (https://github.com/upptime/upptime) -->
<!-- Do not edit this manually, your changes will be overwritten -->
<!-- prettier-ignore -->

## 🛠️ Tools
| URL | Status | History | Response Time | Uptime |
| --- | ------ | ------- | ------------- | ------ |
MARKER
cat tools >> "$README"
cat >> "$README" << 'MARKER'

## ☁️ Clusters
| URL | Status | History | Response Time | Uptime |
| --- | ------ | ------- | ------------- | ------ |
MARKER
cat clusters >> "$README"
echo "" >> "$README"
echo "<!--end: status pages-->" >> "$README"
cat suffix >> "$README"

rm -f prefix suffix tools clusters
